#!/usr/bin/env python3
"""通用 SVG -> LVGL I1 转换与 catalog C 代码生成。"""
from __future__ import annotations

import io
import re
from pathlib import Path

from PIL import Image
from reportlab.graphics import renderPM
from svglib.svglib import svg2rlg

VARIANT_VALUES = {"default": 0, "small": 1, "large": 2}
PALETTE = bytes([0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0xFF])


def render_svg(path: Path, size: int) -> Image.Image:
    drawing = svg2rlg(str(path))
    if drawing is None:
        raise ValueError(f"SVG 解析失败: {path}")
    drawing.scale(size / 16.0, size / 16.0)
    drawing.width = size
    drawing.height = size
    png = renderPM.drawToString(drawing, fmt="PNG", bg=0xFFFFFF)
    return Image.open(io.BytesIO(png)).convert("L")


def encode_i1(image: Image.Image, threshold: int = 128) -> tuple[bytes, int]:
    width, height = image.size
    stride = ((width + 7) // 8 + 3) // 4 * 4
    pixels = image.load()
    output = bytearray(PALETTE)
    for y in range(height):
        row = bytearray(stride)
        for x in range(width):
            if pixels[x, y] < threshold:
                row[x // 8] |= 0x80 >> (x % 8)
        output.extend(row)
    return bytes(output), stride


def symbol_part(value: object) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", str(value)).lower()


def emit_array(name: str, data: bytes) -> str:
    values = ",".join(f"0x{value:02x}" for value in data)
    return f"static const uint8_t {name}[] = {{{values}}};\n"


def emit_descriptor(name: str, array: str, size: int, stride: int, data_size: int) -> str:
    return f"""static const lv_image_dsc_t {name} = {{
  .header = {{
    .magic = LV_IMAGE_HEADER_MAGIC,
    .cf = LV_COLOR_FORMAT_I1,
    .flags = 0,
    .w = {size},
    .h = {size},
    .stride = {stride},
    .reserved_2 = 0,
  }},
  .data_size = {data_size},
  .data = {array},
  .reserved = NULL,
}};
"""


def expand_assets(manifest: dict) -> list[dict]:
    source_pattern = manifest.get("source_pattern", "{name}.svg")
    assets: list[dict] = []
    if "keys" in manifest:
        for key in manifest["keys"]:
            assets.append({"key": int(key), "name": str(key), "source": source_pattern.format(key=key, name=key)})
    for item in manifest.get("assets", []):
        key = int(item["key"])
        name = item.get("name", str(key))
        assets.append({"key": key, "name": name, "source": item.get("source", source_pattern.format(key=key, name=name))})
    return assets


def generate(manifest: dict, project_root: Path) -> tuple[str, str]:
    catalog = symbol_part(manifest["catalog"])
    source_root = project_root / manifest["source_root"]
    variants = manifest["variants"]
    records: list[tuple[int, int, str, bytes, int, int]] = []
    seen: set[tuple[int, int]] = set()

    for asset in expand_assets(manifest):
        source = source_root / asset["source"]
        if not source.is_file():
            raise FileNotFoundError(f"缺少图片源文件: {source}")
        for variant_name, size in variants.items():
            if variant_name not in VARIANT_VALUES:
                raise ValueError(f"未知 variant: {variant_name}")
            pair = (asset["key"], VARIANT_VALUES[variant_name])
            if pair in seen:
                raise ValueError(f"重复 key/variant: {pair}")
            seen.add(pair)
            image = render_svg(source, int(size))
            data, stride = encode_i1(image, int(manifest.get("threshold", 128)))
            symbol = f"{catalog}_{symbol_part(asset['name'])}_{variant_name}"
            records.append((pair[0], pair[1], symbol, data, stride, int(size)))

    records.sort(key=lambda item: (item[0], item[1]))
    count_macro = f"{catalog.upper()}_I1_ENTRY_COUNT"
    header = f"""/* AUTO-GENERATED by tools/weather_icons/generate.py. 不要手改。 */
#pragma once

#include <stddef.h>
#include "ui_platform_image.h"

#define {count_macro} {len(records)}U

extern const ui_platform_image_entry_t {catalog}_i1_entries[];
extern const size_t {catalog}_i1_entry_count;
"""
    source_lines = [
        "/* AUTO-GENERATED by tools/weather_icons/generate.py. 不要手改。 */",
        f'#include "{Path(manifest["outputs"]["h"]).name}"',
        "",
    ]
    for _, _, symbol, data, stride, size in records:
        source_lines.append(emit_array(f"{symbol}_map", data))
        source_lines.append(emit_descriptor(symbol, f"{symbol}_map", size, stride, len(data)))
    source_lines.append(f"const ui_platform_image_entry_t {catalog}_i1_entries[] = {{")
    for key, variant, symbol, *_ in records:
        source_lines.append(f"    {{ {key}U, (ui_platform_image_variant_t){variant}, &{symbol} }},")
    source_lines.extend((
        "};",
        f"const size_t {catalog}_i1_entry_count =",
        f"    sizeof({catalog}_i1_entries) / sizeof({catalog}_i1_entries[0]);",
        "",
    ))
    return "\n".join(source_lines), header
